# -*- coding: UTF-8 -*-
####################################################################################################################
# Generated by Warband Module Decompiler
# All rights of the module belong to their respective owners
####################################################################################################################

import string
from module_info import *

dword      = 0x8000000000000000
dword_mask = 0xffffffffffffffff

density_bits      = 32
fkf_density_mask  = 0xFFFF #16K

#terain condition flags
fkf_plain             = 0x00000004
fkf_steppe            = 0x00000008
fkf_snow              = 0x00000010
fkf_desert            = 0x00000020
fkf_plain_forest      = 0x00000400
fkf_steppe_forest     = 0x00000800
fkf_snow_forest       = 0x00001000
fkf_desert_forest     = 0x00002000
fkf_terrain_mask      = 0x0000ffff

fkf_realtime_ligting  = 0x00010000 #deprecated
fkf_point_up          = 0x00020000 #uses auto-generated point-up(quad) geometry for the flora kind
fkf_align_with_ground = 0x00040000 #align the flora object with the ground normal
fkf_grass             = 0x00080000 #is grass
fkf_on_green_ground   = 0x00100000 #populate this flora on green ground
fkf_rock              = 0x00200000 #is rock 
fkf_tree              = 0x00400000 #is tree -> note that if you set this parameter, you should pass additional alternative tree definitions
fkf_snowy             = 0x00800000
fkf_guarantee         = 0x01000000

fkf_speedtree         = 0x02000000  #NOT FUNCTIONAL: we have removed speedtree support on M&B Warband

fkf_has_colony_props  = 0x04000000  # if fkf_has_colony_props -> then you can define colony_radius and colony_treshold of the flora kind


def density(g):
  if (g > fkf_density_mask):
    g = fkf_density_mask
  return ((dword | g) << density_bits)


fauna_kinds = [
  ("grass", density(750)|fkf_plain|fkf_plain_forest|fkf_point_up|fkf_align_with_ground|fkf_grass|fkf_on_green_ground|fkf_guarantee, [["grass_a", "0"],["grass_b", "0"],["grass_c", "0"],["grass_d", "0"],["grass_e", "0"]]),
  ("grass_bush", density(5)|fkf_plain|fkf_align_with_ground|fkf_grass, [["grass_bush_a", "0"],["grass_bush_b", "0"]]),
  ("grass_saz", density(250)|fkf_grass|fkf_on_green_ground, [["grass_bush_c", "0"],["grass_bush_d", "0"]]),
  ("grass_purple", density(250)|fkf_plain|fkf_grass, [["grass_bush_e", "0"],["grass_bush_f", "0"]]),
  ("fern", density(500)|fkf_plain_forest|fkf_align_with_ground|fkf_grass, [["fern_a", "0"],["fern_b", "0"]]),
  ("grass_steppe", density(500)|fkf_steppe|fkf_steppe_forest|fkf_point_up|fkf_align_with_ground|fkf_grass|fkf_guarantee, [["grass_yellow_a", "0"],["grass_yellow_b", "0"],["grass_yellow_c", "0"],["grass_yellow_d", "0"],["grass_yellow_e", "0"]]),
  ("grass_bush_g", density(250)|fkf_plain|fkf_plain_forest|fkf_align_with_ground|fkf_grass, [["grass_bush_g01", "0"],["grass_bush_g02", "0"],["grass_bush_g03", "0"]]),
  ("grass_bush_h", density(250)|fkf_plain|fkf_plain_forest|fkf_align_with_ground|fkf_grass, [["grass_bush_h01", "0"],["grass_bush_h02", "0"],["grass_bush_h03", "0"]]),
  ("grass_bush_i", density(250)|fkf_plain|fkf_plain_forest|fkf_align_with_ground|fkf_grass, [["grass_bush_i01", "0"],["grass_bush_i02", "0"]]),
  ("grass_bush_j", density(250)|fkf_plain|fkf_plain_forest|fkf_align_with_ground|fkf_grass, [["grass_bush_j01", "0"],["grass_bush_j02", "0"]]),
  ("grass_bush_k", density(250)|fkf_plain|fkf_plain_forest|fkf_align_with_ground|fkf_grass, [["grass_bush_k01", "0"],["grass_bush_k02", "0"]]),
  ("grass_bush_l", density(25)|fkf_plain|fkf_plain_forest|fkf_align_with_ground, [["grass_bush_l01", "0"],["grass_bush_l02", "0"]]),
  ("thorn_a", density(25)|fkf_plain|fkf_plain_forest|fkf_align_with_ground, [["thorn_a", "0"],["thorn_b", "0"],["thorn_c", "0"],["thorn_d", "0"]]),
  ("basak", density(35)|fkf_plain|fkf_plain_forest, [["basak", "0"]]),
  ("common_plant", density(35)|fkf_plain|fkf_steppe|fkf_plain_forest|fkf_steppe_forest, [["common_plant", "0"]]),
  ("small_plant", density(25)|fkf_plain|fkf_plain_forest|fkf_align_with_ground, [["small_plant", "0"],["small_plant_b", "0"],["small_plant_c", "0"]]),
  ("buddy_plant", density(25)|fkf_plain|fkf_plain_forest, [["buddy_plant", "0"],["buddy_plant_b", "0"]]),
  ("yellow_flower", density(25)|fkf_plain|fkf_plain_forest|fkf_align_with_ground, [["yellow_flower", "0"],["yellow_flower_b", "0"]]),
  ("spiky_plant", density(25)|fkf_plain|fkf_plain_forest|fkf_align_with_ground, [["spiky_plant", "0"]]),
  ("seedy_plant", density(25)|fkf_plain|fkf_steppe|fkf_plain_forest|fkf_steppe_forest, [["seedy_plant_a", "0"]]),
  ("blue_flower", density(15)|fkf_plain|fkf_plain_forest, [["blue_flower", "0"]]),
  ("big_bush", density(15)|fkf_plain|fkf_plain_forest, [["big_bush", "0"]]),
  ("bushes02_a", density(15)|fkf_plain|fkf_plain_forest, [["bushes02_a", "bo_bushes02_a"],["bushes02_b", "bo_bushes02_b"],["bushes02_c", "bo_bushes02_c"]]),
  ("bushes03_a", density(15)|fkf_plain|fkf_plain_forest, [["bushes03_a", "0"],["bushes03_b", "0"],["bushes03_c", "0"]]),
  ("bushes04_a", density(35)|fkf_plain|fkf_plain_forest, [["bushes04_a", "0"],["bushes04_b", "0"],["bushes04_c", "0"]]),
  ("bushes05_a", density(35)|fkf_plain|fkf_plain_forest, [["bushes05_a", "0"],["bushes05_b", "0"],["bushes05_c", "0"]]),
  ("bushes06_a", density(35)|fkf_plain|fkf_plain_forest, [["bushes06_a", "0"],["bushes06_b", "0"],["bushes06_c", "0"]]),
  ("bushes07_a", density(35)|fkf_plain|fkf_plain_forest, [["bushes07_a", "bo_bushes07_a"],["bushes07_b", "bo_bushes07_b"],["bushes07_c", "0"]]),
  ("bushes08_a", density(35)|fkf_plain|fkf_plain_forest, [["bushes08_a", "0"],["bushes08_b", "0"],["bushes08_c", "0"]]),
  ("bushes09_a", density(35)|fkf_plain|fkf_plain_forest, [["bushes09_a", "bo_bushes09_a"],["bushes09_b", "bo_bushes09_b"],["bushes09_c", "bo_bushes09_c"]]),
  ("bushes10_a", density(35)|fkf_plain|fkf_plain_forest, [["bushes10_a", "bo_bushes10_a"],["bushes10_b", "bo_bushes10_b"],["bushes10_c", "bo_bushes10_c"]]),
  ("bushes11_a", density(35)|fkf_plain|fkf_plain_forest, [["bushes11_a", "0"],["bushes11_b", "0"],["bushes11_c", "0"]]),
  ("bushes12_a", density(25)|fkf_plain|fkf_plain_forest|fkf_align_with_ground, [["bushes12_a", "0"],["bushes12_b", "0"],["bushes12_c", "0"]]),
  ("aspen", density(35)|fkf_plain|fkf_plain_forest, [["tree_14_a", "bo_tree_14_a"],["tree_14_b", "bo_tree_14_b"],["tree_14_c", "bo_tree_14_c"]]),
  ("pine_1", density(4)|fkf_plain|fkf_plain_forest|fkf_tree, [("pine_1_a", "bo_pine_1_a",("0","0")),("pine_1_b", "bo_pine_1_b",("0","0"))]),
  ("pine_2", density(4)|fkf_plain|fkf_plain_forest|fkf_tree, [("pine_2_a", "bo_pine_2_a",("0","0"))]),
  ("pine_3", density(4)|fkf_plain|fkf_plain_forest|fkf_tree, [("pine_3_a", "bo_pine_3_a",("0","0"))]),
  ("pine_4", density(4)|fkf_plain|fkf_plain_forest|fkf_tree, [("pine_4_a", "bo_pine_4_a",("0","0"))]),
  ("pine_6", density(4)|fkf_plain|fkf_plain_forest|fkf_tree, [("pine_6_a", "bo_pine_6_a",("0","0"))]),
  ("snowy_pine", density(5)|fkf_snow|fkf_snow_forest|fkf_tree, [("tree_snowy_a", "bo_tree_snowy_a",("0","0"))]),
  ("snowy_pine_2", density(5)|fkf_snow|fkf_snow_forest|fkf_tree, [("snowy_pine_2", "bo_snowy_pine_2",("0","0"))]),
  ("small_rock", density(4)|fkf_plain|fkf_plain_forest|fkf_tree, [("tree_17_a", "bo_tree_17_a",("0","0")),("tree_17_b", "bo_tree_17_b",("0","0")),("tree_17_c", "bo_tree_17_c",("0","0"))]),
  ("rock_snowy", density(5)|fkf_snow|fkf_snow_forest|fkf_realtime_ligting|fkf_rock, [["rock_snowy_a", "bo_rock_snowy_a"],["rock_snowy_b", "bo_rock_snowy_b"],["rock_snowy_c", "bo_rock_snowy_c"]]),
  ("rock", density(35)|fkf_plain|fkf_plain_forest, [["pine_1_a", "bo_pine_1_a"],["pine_1_b", "bo_pine_1_b"],["bushes06_c", "0"]]),
  ("rock_snowy2", density(5)|fkf_snow|fkf_snow_forest|fkf_realtime_ligting|fkf_rock, [["tree_snowy_b", "bo_tree_snowy_b"],["tree_snowy_b", "bo_tree_snowy_b"],["tree_snowy_b", "bo_tree_snowy_b"]]),
  ("tree_1", density(35)|fkf_plain|fkf_plain_forest, [["tree_2_a", "bo_tree_2_a"],["tree_2_b", "bo_tree_2_b"]]),
  ("tree_3", density(5)|fkf_snow|fkf_snow_forest|fkf_realtime_ligting|fkf_rock, [["tree_3_a", "0"],["tree_3_b", "0"]]),
  ("bush_snowy", density(5)|fkf_snow|fkf_snow_forest|fkf_realtime_ligting|fkf_rock, [["tree_3_a", "0"],["tree_3_b", "0"]]),
  ("bush_snowy2", density(5)|fkf_snow|fkf_snow_forest|fkf_realtime_ligting|fkf_rock, [["tree_3_a", "0"],["tree_3_b", "0"]]),
  ("bush_snowy3", density(5)|fkf_snow|fkf_snow_forest|fkf_tree, [("tree_3_a", "0",("0","0")),("tree_3_b", "0",("0","0"))]),
  ("bush_snowy4", density(5)|fkf_snow|fkf_snow_forest|fkf_tree, [("tree_3_a", "0",("0","0")),("tree_3_b", "0",("0","0"))]),
  ("bush_snowy5", density(5)|fkf_snow|fkf_snow_forest|fkf_realtime_ligting|fkf_rock, [["tree_3_a", "0"],["tree_3_b", "0"]]),
  ("bush_snowy6", density(5)|fkf_snow|fkf_snow_forest|fkf_tree, [("tree_3_a", "0",("0","0")),("tree_3_b", "0",("0","0"))]),
  ("grass_snowy1", density(5)|fkf_snow|fkf_snow_forest|fkf_realtime_ligting|fkf_rock, [["bushes06_a", "0"]]),
  ("grass_snowy1b", density(5)|fkf_snow|fkf_snow_forest|fkf_realtime_ligting|fkf_rock, [["wi_bush1", "0"]]),
  ("grass_snowy2", density(5)|fkf_snow|fkf_snow_forest|fkf_realtime_ligting|fkf_rock, [["wi_bush2a", "0"]]),
  ("grass_snowy2b", density(5)|fkf_snow|fkf_snow_forest|fkf_realtime_ligting|fkf_rock, [["wi_bush2b", "0"]]),
  ("grass_snowy3a", density(5)|fkf_snow|fkf_snow_forest|fkf_realtime_ligting|fkf_rock, [["wi_bush3a", "0"]]),
  ("grass_snowy3b", density(5)|fkf_snow|fkf_snow_forest|fkf_realtime_ligting|fkf_rock, [["wi_bush3b", "0"]]),
  ("grass_snowy1", density(5)|fkf_snow|fkf_snow_forest|fkf_realtime_ligting|fkf_rock, [["bushes06_b", "0"]]),
  ("grass_snowy1b", density(5)|fkf_snow|fkf_snow_forest|fkf_realtime_ligting|fkf_rock, [["wi_bush1", "0"]]),
  ("grass_snowy2", density(5)|fkf_snow|fkf_snow_forest|fkf_realtime_ligting|fkf_rock, [["wi_bush2a", "0"]]),
  ("grass_snowy2b", density(5)|fkf_snow|fkf_snow_forest|fkf_realtime_ligting|fkf_rock, [["wi_bush2b", "0"]]),
  ("grass_snowy3a", density(5)|fkf_snow|fkf_snow_forest|fkf_realtime_ligting|fkf_rock, [["wi_bush3a", "0"]]),
  ("grass_snowy3b", density(5)|fkf_snow|fkf_snow_forest|fkf_realtime_ligting|fkf_rock, [["wi_bush3b", "0"]]),
  ("tree_4", density(4)|fkf_plain|fkf_plain_forest|fkf_tree, [("tree_20_a", "bo_tree_20_a",("0","0")),("tree_20_b", "bo_tree_20_b",("0","0"))]),
  ("tree_5", density(35)|fkf_plain|fkf_plain_forest, [["tree_5_a", "bo_tree_5_a"],["tree_5_b", "bo_tree_5_b"],["tree_5_c", "bo_tree_5_c"],["tree_5_d", "bo_tree_5_d"]]),
  ("tree_6", density(4)|fkf_plain|fkf_plain_forest|fkf_tree, [("tree_6_a", "bo_tree_6_a",("0","0")),("tree_6_b", "bo_tree_6_b",("0","0")),("tree_6_c", "bo_tree_6_c",("0","0")),("tree_6_d", "bo_tree_6_d",("0","0"))]),
  ("tree_7", density(4)|fkf_plain|fkf_plain_forest|fkf_tree, [("tree_7_a", "0",("0","0")),("tree_7_b", "0",("0","0")),("tree_7_c", "0",("0","0"))]),
  ("tree_8", density(4)|fkf_plain|fkf_plain_forest|fkf_tree, [("tree_8_a", "0",("0","0")),("tree_8_b", "0",("0","0"))]),
  ("tree_9", density(25)|fkf_plain|fkf_plain_forest|fkf_align_with_ground, [["thorn_a", "0"],["thorn_b", "0"],["thorn_c", "0"]]),
  ("tree_10", density(4)|fkf_plain|fkf_plain_forest|fkf_tree, [("tree_10_a", "bo_tree_10_a",("0","0")),("tree_10_b", "bo_tree_10_b",("0","0")),("tree_10_c", "bo_tree_10_c",("0","0"))]),
  ("tree_11", density(4)|fkf_plain|fkf_plain_forest|fkf_tree, [("tree_11_a", "bo_tree_11_a",("0","0")),("tree_11_b", "bo_tree_11_b",("0","0")),("tree_11_c", "bo_tree_11_c",("0","0"))]),
  ("tree_12", density(4)|fkf_plain|fkf_plain_forest|fkf_tree, [("tree_12_a", "bo_tree_12_a",("0","0")),("tree_12_b", "bo_tree_12_b",("0","0")),("tree_12_c", "bo_tree_12_c",("0","0"))]),
  ("tree_14", density(35)|fkf_plain|fkf_plain_forest, [["tree_14_a", "bo_tree_14_a"],["tree_14_b", "bo_tree_14_b"],["tree_14_c", "bo_tree_14_c"]]),
  ("tree_15", density(35)|fkf_plain|fkf_plain_forest, [["tree_15_a", "bo_tree_15_a"],["tree_15_b", "bo_tree_15_b"],["tree_15_b", "bo_tree_15_b"]]),
  ("tree_16", density(35)|fkf_plain|fkf_plain_forest, [["rock_d", "bo_rock_d"],["rock_i", "bo_rock_i"]]),
  ("tree_17", density(4)|fkf_plain|fkf_plain_forest|fkf_tree, [("tree_17_a", "bo_tree_17_a",("0","0")),("tree_17_b", "bo_tree_17_b",("0","0")),("tree_17_c", "bo_tree_17_c",("0","0")),("tree_17_d", "bo_tree_17_d",("0","0"))]),
  ("palm", density(4)|fkf_desert_forest|fkf_tree, [("palm_a", "bo_palm_a",("0","0"))]),
  ("tree_new_1", density(15)|fkf_plain|fkf_plain_forest, [["tree_5_a", "bo_tree_5_a"],["tree_5_b", "bo_tree_5_b"]]),
  ("bush_new_1", density(35)|fkf_plain|fkf_plain_forest, [["bushes10_a", "bo_bushes10_a"],["bushes10_b", "bo_bushes10_b"]]),
  ("bush_new_2", density(35)|fkf_plain|fkf_plain_forest, [["bushes06_a", "0"]]),
  ("bush_new_3", density(4)|fkf_plain|fkf_plain_forest|fkf_tree, [("rock_h", "bo_rock_h",("0","0")),("rock_i", "bo_rock_i",("0","0")),("rock_d", "bo_rock_d",("0","0")),("rock_f", "bo_rock_f",("0","0"))]),
  ("bush_new_4", density(35)|fkf_plain|fkf_plain_forest, [["rock_d", "bo_rock_d"],["rock_i", "bo_rock_i"]]),
  ("dry_bush", density(35)|fkf_plain|fkf_plain_forest, [["dry_bush", "0"]]),
  ("dry_leaves", density(35)|fkf_plain|fkf_plain_forest, [["dry_leaves", "0"]]),
  ("tree_new_2", density(4)|fkf_plain|fkf_plain_forest|fkf_tree, [("tree_11_a", "bo_tree_11_a",("0","0")),("tree_11_b", "bo_tree_11_b",("0","0"))]),
  ("tree_new_3", density(4)|fkf_plain|fkf_plain_forest|fkf_tree, [("tree_11_b", "bo_tree_11_b",("0","0")),("tree_11_c", "bo_tree_11_c",("0","0"))]),
  ("tree_plane", density(4)|fkf_plain|fkf_plain_forest|fkf_tree, [("tree_16_a", "bo_tree_16_a",("0","0")),("tree_16_b", "bo_tree_16_b",("0","0"))]),
  ("tree_19", density(5)|fkf_snow|fkf_snow_forest|fkf_realtime_ligting|fkf_rock, [["tree_19_a", "bo_tree_19_a"]]),
  ("beech", density(3)|fkf_plain|fkf_plain_forest|fkf_tree, [("tree_17_a", "bo_tree_17_a",("0","0")),("tree_17_b", "bo_tree_17_b",("0","0"))]),
  ("tall_tree", density(4)|fkf_plain|fkf_plain_forest|fkf_tree, [("tree_f_1", "bo_tree_f_1",("0","0"))]),
  ("tree_e", density(4)|fkf_plain|fkf_plain_forest|fkf_tree, [("tree_e_1", "bo_tree_e_1",("0","0")),("tree_e_2", "bo_tree_e_2",("0","0")),("tree_e_3", "bo_tree_e_3",("0","0"))]),
  ("tree_f", density(4)|fkf_plain|fkf_plain_forest|fkf_tree, [("tree_f_1", "bo_tree_f_1",("0","0")),("tree_f_2", "bo_tree_f_2",("0","0")),("tree_f_3", "bo_tree_f_3",("0","0"))]),
  ("grape_vineyard", 0, [["grape_vineyard", "bo_grape_vineyard"]]),
  ("grape_vineyard_stake", 0, [["grape_vineyard_stake", "bo_grape_vineyard_stake"]]),
  ("wheat", density(4)|fkf_plain|fkf_plain_forest, [["wheat_a", "0"],["wheat_b", "0"],["wheat_c", "0"],["wheat_d", "0"]]),
  ("valleyRock_rounded", density(5)|fkf_rock, [["valleyRock_rounded_1", "bo_valleyRock_rounded_1"],["valleyRock_rounded_2", "bo_valleyRock_rounded_2"],["valleyRock_rounded_3", "bo_valleyRock_rounded_3"],["valleyRock_rounded_4", "bo_valleyRock_rounded_4"]]),
  ("valleyRock_flat", density(5)|fkf_rock, [["valleyRock_flat_1", "bo_valleyRock_flat_1"],["valleyRock_flat_2", "bo_valleyRock_flat_2"],["valleyRock_flat_3", "bo_valleyRock_flat_3"],["valleyRock_flat_4", "bo_valleyRock_flat_4"],["valleyRock_flat_5", "bo_valleyRock_flat_5"],["valleyRock_flat_6", "bo_valleyRock_flat_6"]]),
  ("valleyRock_flatRounded_small", density(5)|fkf_rock, [["valleyRock_flatRounded_small_1", "bo_valleyRock_flatRounded_small_1"],["valleyRock_flatRounded_small_2", "bo_valleyRock_flatRounded_small_2"],["valleyRock_flatRounded_small_3", "bo_valleyRock_flatRounded_small_3"]]),
  ("valleyRock_flatRounded_big", density(5)|fkf_rock, [["valleyRock_flatRounded_big_1", "bo_valleyRock_flatRounded_big_1"],["valleyRock_flatRounded_big_2", "bo_valleyRock_flatRounded_big_2"]]),
]
def save_fauna_kinds():
  file = open(export_dir + "Data/flora_kinds.txt","w")
  file.write("%d\n"%len(fauna_kinds))
  for fauna_kind in fauna_kinds:
    meshes_list = fauna_kind[2]
    file.write("%s %d %d\n"%(fauna_kind[0], (dword_mask & fauna_kind[1]), len(meshes_list)))
    for m in meshes_list:
      file.write(" %s "%(m[0]))
      if (len(m) > 1):
        file.write(" %s\n"%(m[1]))
      else:
        file.write(" 0\n")
      if ( fauna_kind[1] & (fkf_tree|fkf_speedtree) ):  #if this fails make sure that you have entered the alternative tree definition (NOT FUNCTIONAL in Warband)
        speedtree_alternative = m[2]
        file.write(" %s %s\n"%(speedtree_alternative[0], speedtree_alternative[1]))
    if ( fauna_kind[1] & fkf_has_colony_props ):
      file.write(" %s %s\n"%(fauna_kind[3], fauna_kind[4]))
  file.close()

def two_to_pow(x):
  result = 1
  for i in xrange(x):
    result = result * 2
  return result

fauna_mask = 0x80000000000000000000000000000000
low_fauna_mask =             0x8000000000000000
def save_python_header():
  file = open("./fauna_codes.py","w")
  for i_fauna_kind in xrange(len(fauna_kinds)):
    file.write("%s_1 = 0x"%(fauna_kinds[i_fauna_kind][0]))
    file.write("%x\n"%(fauna_mask | two_to_pow(i_fauna_kind)))
    file.write("%s_2 = 0x"%(fauna_kinds[i_fauna_kind][0]))
    file.write("%x\n"%(fauna_mask | ((low_fauna_mask|two_to_pow(i_fauna_kind)) << 64)))
    file.write("%s_3 = 0x"%(fauna_kinds[i_fauna_kind][0]))
    file.write("%x\n"%(fauna_mask | ((low_fauna_mask|two_to_pow(i_fauna_kind)) << 64) | two_to_pow(i_fauna_kind)))
  file.close()

print "Exporting flora data..."
save_fauna_kinds()